### PR TITLE
[NOT READY] area search for mosaic quads

### PR DESCRIPTION
**Pull request by kapadia**
@ischneider want to flag you on this. I've been in need of AOI search for mosaic quads. This should do it, however, there's an outstanding bug with the API that prevents it's usage.

### CODE REVIEW

**Comment by ischneider** [comment]
Right, see #60. Thanks @kapadia

**Comment by kapadia** [comment]
Cool. Can't wait for that support.

**Comment by ischneider** [comment]
For fun, I tried with just the geometry from a feature collection and this works.

**Comment by kapadia** [comment]
Awesome.

**Pull request merged**
