### PR TITLE
Remove filter requirement for data quick search, planet data filter cli command outputs empty filter by default

### LINKED ISSUE #600: Don't require a filter for a quick search.
To solve the issues below, do the following:
1. In quick search, make filter a named option (`--filter` for CLI, `search_filter` for api), if not supplied then no filtering will take place
2. Change `planet data filter` to output an empty filter (no filtering) by default so that `planet data filter | planet search PSScene --filter -` has the same behavior as `planet search PSScene` - this resolves #704 

---

If I try to do a quick search with no filter I get:

```
% planet data search-quick PSScene                                                              

Usage: planet data search-quick [OPTIONS] ITEM_TYPES FILTER

Try 'planet data search-quick --help' for help.

Error: Missing argument 'FILTER'.
```

In v1 doing a search without a filter would just show you the latest data. 

Right now you can do `planet data filter | planet data search-quick SkysatCollect -`, since filter outputs `{"type": "PermissionFilter", "config": ["assets:download"]}` by default.

But then if you didn't want to only search downloadable assets you could do:

`planet data filter --permission false | planet data search-quick SkysatCollect -` and then you get a failure, since the latter doesn't actually output a filter, it emits nothing.

### PR DESCRIPTION
**Pull request by jreiberkyle**
**Related Issue(s):**

Closes #600 #704 #637

**Proposed Changes:**

For inclusion in changelog (if applicable):

1. Data client CLI and API no longer require filter to be specified, and will use an empty filter (no filtering) if it is not. Filter moved from a positional argument for the CLI and API to an optional key word argument, `--filter` for the CLI and `search_filter` for the API.
2. Data filter CLI command now outputs an empty filter by default, it no longer includes permissions and standard quality filters by default, these are easily added with the `--permissions` and `--std-quality` flags

Not intended for changelog:

1. Update CLI docs to use new interface. Change wording some to discuss permissions and standard quality filters not being defaults but being easy to add. @JuLeeAtPlanet FYI

**Diff of User Interface**

#### Planet data filter
Old behavior:

`planet data filter` outputs a permissions and standard quality filter by default
```
> planet data filter
{"type": "AndFilter", "config": [{"type": "PermissionFilter", "config": ["assets:download"]}, {"type": "StringInFilter", "field_name": "quality_category", "config": ["standard"]}]}
```

to get an empty filter use
```
> planet data filter 
{"type": "AndFilter", "config": []}
```

New behavior:
`planet data filter` outputs an empty filter by default
```
> planet data filter
{"type": "AndFilter", "config": []}
```
to get a permissions/std-quality filter:
```
> planet data filter --permission --std-quality
{"type": "AndFilter", "config": [{"type": "PermissionFilter", "config": ["assets:download"]}, {"type": "StringInFilter", "field_name": "quality_category", "config": ["standard"]}]}
```

#### Planet quick search, CLI
Old behavior:

`planet data search PSScene filter.json` applies filter to search, returns at most 100 results

`planet data search PSScene` errors out due to FILTER being a required argument

New behavior:

`planet data search PSScene -filter filter.json` applies filter to search

`planet data search PSScene` returns 100 (default value of limit) results

#### Planet quick search, API
Old behavior:
```python
data_client.search(['PSScene'], filter)
```
applies filter to search

```python
data_client.search(['PSScene'])
```
Errors out due to search_filter being a required argument

New behavior:

```python
data_client.search(['PSScene'], search_filter=filter)
```
applies filter to search

```python
data_client.search(['PSScene'])
```
Returns 100 (default value of limit) results

**PR Checklist:**

- [x] This PR is as small and focused as possible
- [x] If this PR includes proposed changes for inclusion in the changelog, the title of this PR summarizes those changes and is ready for inclusion in the Changelog.
- [x] I have updated docstrings for function changes and docs in the 'docs' folder for user interface / behavior changes
- [x] This PR does not break any examples or I have updated them

**(Optional) @mentions for Notifications:**
@cholmes @JuLeeAtPlanet

### CODE REVIEW

**Comment by jreiberkyle** [comment]
@julee could you look at content changes?
@cholmes could you look at usage pattern?
@kevinlacaille could you do a code review?
TY!

**Review by cholmes — APPROVED** [review]
Looks great, works great in my limited testing.

I think the only thing in here that will be subtly confusing, especially in evolution from the current thing, is that:

`planet data filter --number-in cloud_percent 4 | planet data search PSScene` won't actually get the filter applied. You need to remember to add `--filter -`. If you've got any ideas on how to nudge people towards that it could be good. Like can we detect if they're attempting to pipe something and warn them that it won't be applied?

**Comment by jreiberkyle** [comment]
@cholmes hmm... yeah, that's a hard one to protect against. There is the option of prompting the user for confirmation (overridden with an `-y` option) when a search is run without a filter. Requires an opt-in for searching without a filter.

**Comment by cholmes** [comment]
Could it just raise a little warning when searching without a filter? 
Like just says 'executing search with no filter'. I don't think we need to keep that warning around forever, just for a few releases to help people adopt new behavior. 

Even better would be if we could detect if there's anything being piped in. Like if it detects some attempted pipe then it would raise that message (or an even stronger warning, since it wouldn't come up every time)

**Review by kevinlacaille — APPROVED** [review]
Everything looks good to me! I can confirm that all tests pass on 3.10 and 3.11.

**Comment by jreiberkyle** [comment]
@cholmes I don't know of a way to check for an attempt to pipe in. Or, if there is a way, it would take a lot of work. I'm also not sure of how to output a warning that wouldn't mess up any further processing of the search results - like if we pipe it to jq then jq will probably croak on the warning message before it can process the results that are the actual outputs.

**Comment by cholmes** [comment]
>  I'm also not sure of how to output a warning that wouldn't mess up any further processing of the search results - like if we pipe it to jq then jq will probably croak on the warning message before it can process the results that are the actual outputs.

Ah, I had been thinking that a warning maybe wouldn't go to stdout in the same way, but you're probably right. Ok, sounds like no easy solution - seems like we should just ship it and be sure to document it all well. Maybe a note / warning somewhere in the docs, and in the release notes, to notify people to watch out for piping without the '-'. New users shouldn't have any trouble with it, and we only have a small number of users today, so it should be fine.

**Pull request merged**
