### PR TITLE
fix hyphens in cli docs

### LINKED ISSUE #115: hyphens vs. underscores in docs
In [the CLI docs](https://planetlabs.github.io/planet-client-python/cli/reference.html?highlight=activate%20only#cli-command-download), `--activate-only`, `--dry-run`, etc. are listed with underscores. The CLI actually expects hyphens between words. Would be nice for this to be consistent.

```shell
planet data download --help
Usage: planet data download [OPTIONS]

  Activate and download

Options:
  --limit NUMBER               Limit the number of items.
  --dest DIRECTORY             Location to download files to
  --quiet                      Disable ANSI control output
  --activate-only              Only activate the items. Outputs URLS for
                               downloading.
  --dry-run                    Only report the number of items that would be
                               downloaded.

etc.
```

### PR DESCRIPTION
**Pull request by cp16net**
Fixes #115

### CODE REVIEW

**Comment by ischneider** [comment]
It's not super obvious but this is a generated file :smile:

The generator is also not very clear :/ https://github.com/planetlabs/planet-client-python/blob/master/docs/source/generate.py but more pleasure than typing all that out

**Comment by cp16net** [comment]
touche @ischneider

**Comment by ischneider** [comment]
See https://github.com/planetlabs/planet-client-python/pull/121

**Comment by cp16net** [comment]
#121 fixes it the "right way" closing this one

**Pull request closed without merging**
