### PR TITLE
Enable permalinks for section headers

### LINKED ISSUE #775: Section links in docs
Our docs need links for section headers. Check out https://mercantile.readthedocs.io/en/stable/cli.html#examples: every section header has a link, which makes it easy to reference sections in online discussions. Mercantile's docs are made using sphinx.

You can see permalinks in action on the Mkdoc docs: https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages. Apparently this feature is disabled by default.

### PR DESCRIPTION
**Pull request by sgillies**
Resolves #775

### CODE REVIEW

**Comment by sgillies** [comment]
Built the docs locally `nox -s docs` and links are enabled. See the ¶ at the end of "Step 1".

Screenshot from 2022-11-17 08-53-44

**Comment by sgillies** [comment]
@jreiberkyle @cholmes @JuLeeAtPlanet tagging you for review.

**Review by cholmes — APPROVED** [review]
Love it. Tested it locally, works great.

**Review by jreiberkyle — APPROVED** [review]

**Comment by jreiberkyle** [comment]
@sgillies ultimately @JuLeeAtPlanet / @cholmes own the docs so in the future feel free to just poll them on doc implementation changes

**Pull request merged**
