### PR TITLE
Force stac to false for GEE deliveries

### PR DESCRIPTION
**Pull request by lobugliop**
Related Issue(s):

Closes https://github.com/planetlabs/planet-client-python/issues/958

**Proposed Changes:**

The Orders API will soon surface validation errors when stac is specified for GEE orders. It may be ergonomic for the CLI to force the stac flag to false, rather than requiring users to specify `--no-stac` for GEE orders.
For inclusion in changelog (if applicable):

1. Orders cli will force stac flag to false for GEE deliveries

Not intended for changelog:

1. 

**Diff of User Interface**

Old behavior:
```
$ planet orders request --name "gee_order" --bundle analytic_8b_sr_udm2 20220913_095949_35_24a5,20220829_095558_47_2479,20220824_101550_14_2403 --item-type PSScene --cloudconfig cloudconfig.json
{"name": "gee_order", "products": [{"item_ids": ["20220913_095949_35_24a5", "20220829_095558_47_2479", "20220824_101550_14_2403"], "item_type": "PSScene", "product_bundle": "analytic_8b_sr_udm2"}], "metadata": {"stac": {}}, "delivery": {<REDACTED>}}}
```
After creating the waiting for the order to complete, we won't see our images available in earth engine

```
$ earthengine ls projects/<project>/assets/<collection> | grep 20220913_095949_35_24a5
$
```

New behavior:
```
$ planet orders request --name "gee_order" --bundle analytic_8b_sr_udm2 20220913_095949_35_24a5,20220829_095558_47_2479,20220824_101550_14_2403 --item-type PSScene --cloudconfig cloudconfig.json
{"name": "gee_order", "products": [{"item_ids": ["20220913_095949_35_24a5", "20220829_095558_47_2479", "20220824_101550_14_2403"], "item_type": "PSScene", "product_bundle": "analytic_8b_sr_udm2"}], "delivery": {<REDACTED>}}}
```

After waiting for the order to complete, our images are available in earth engine
```
$ earthengine ls projects/<project>/assets/<collection> | grep 20220913_095949_35_24a5
projects/<project>/assets/<collection>/20220913_095949_35_24a5_3B_AnalyticMS_SR_8b
```

### CODE REVIEW

**Comment by kevinlacaille** [comment]
CC: @cholmes & @JuLeeAtPlanet

**Comment by cholmes** [comment]
Why can't we just have the orders API not create errors when STAC is specified for GEE output? I had thought that was the plan. It seems like an extra file shouldn't cause an error.

**Comment by lobugliop** [comment]
> Why can't we just have the orders API not create errors when STAC is specified for GEE output? I had thought that was the plan. It seems like an extra file shouldn't cause an error.

It just ends up being wasted work, as none of the files/metadata from STAC will be passed through to our delivery to GEE. It could also be confusing UX, because the properties attached to each image in GEE won't be from the STAC output, but from metadata.json/data api

**Comment by kevinlacaille** [comment]
**CLI:**
Using this `cloudconfig.json`:
```json
{
    "google_earth_engine": {
        "project": "planet-devrel-dev",
        "collection": "gee-integration-testing"
    }
}
```

I am able to successfully deliver to GEE:
```console
❯ planet orders request --name "gee_order" --bundle analytic_8b_sr_udm2 20220913_095949_35_24a5,20220829_095558_47_2479,20220824_101550_14_2403 --item-type PSScene --cloudconfig ../jsons_for_tests/cloudconfig.json | planet orders create -

{"_links": {"_self": "https://api.planet.com/compute/ops/orders/v2/5db3d79d-b930-4cf0-adc6-b2a4530fe334"}, "created_on": "2023-06-01T20:32:40.224Z", "delivery": {"google_earth_engine": {"collection": "gee-integration-testing", "credentials": "<REDACTED>", "project": "planet-devrel-dev"}}, "error_hints": [], "id": "5db3d79d-b930-4cf0-adc6-b2a4530fe334", "last_message": "Preparing order", "last_modified": "2023-06-01T20:32:40.224Z", "name": "gee_order", "products": [{"item_ids": ["20220913_095949_35_24a5", "20220829_095558_47_2479", "20220824_101550_14_2403"], "item_type": "PSScene", "product_bundle": "analytic_8b_sr_udm2"}], "state": "queued"}
```
Order status: https://orders-ui.prod.planet-labs.com/orders/5db3d79d-b930-4cf0-adc6-b2a4530fe334

I also get a successful order, even when asking for `--stac`:
```console
❯ planet orders request --name "gee_order" --bundle analytic_8b_sr_udm2 20220913_095949_35_24a5,20220829_095558_47_2479,20220824_101550_14_2403 --item-type PSScene --cloudconfig ../jsons_for_tests/cloudconfig.json --stac | planet orders create -

{"_links": {"_self": "https://api.planet.com/compute/ops/orders/v2/7e97b9c0-07cb-430a-8dfa-a6f626bf486b"}, "created_on": "2023-06-01T20:35:30.829Z", "delivery": {"google_earth_engine": {"collection": "gee-integration-testing", "credentials": "<REDACTED>", "project": "planet-devrel-dev"}}, "error_hints": [], "id": "7e97b9c0-07cb-430a-8dfa-a6f626bf486b", "last_message": "Preparing order", "last_modified": "2023-06-01T20:35:30.829Z", "name": "gee_order", "products": [{"item_ids": ["20220913_095949_35_24a5", "20220829_095558_47_2479", "20220824_101550_14_2403"], "item_type": "PSScene", "product_bundle": "analytic_8b_sr_udm2"}], "state": "queued"}
```
Order status: https://orders-ui.prod.planet-labs.com/orders/7e97b9c0-07cb-430a-8dfa-a6f626bf486b

**SDK:**
When running this through the SDK, similar to how it's done in this notebook, [gee-integration.ipynb](https://github.com/planetlabs/notebooks/blob/master/jupyter-notebooks/gee-integration/gee-integration.ipynb), I get a successful delivery, even when requesting STAC metadata. Namely,
```python
my_order = planet.order_request.build_request(name='iowa_order',
                                                products=data_products,
                                                delivery=delivery_config,
                                                stac={})
```
Order status: https://orders-ui.prod.planet-labs.com/orders/9acf3cca-648e-420a-838b-5551f3103d42

**Pull request merged**
