### PR TITLE
Enable querying by saved aoi.

### PR DESCRIPTION
**Pull request by jacobstr**

### CODE REVIEW

**Comment by jacobstr** [comment]
cc @ischneider

**Comment by jacobstr** [comment]
Any idea why the tests started failing?

**Comment by jacobstr** [comment]
Possibly flake8 was modified upstream and introduced new rules?

**Comment by ischneider** [comment]
@jacobstr It does look like flake8 changes mucked things up. Will look at now

**Comment by ischneider** [comment]
LGTM. Does it make sense to enable listing AOI as well? On that note, I see the version was bumped. I usually do this with a single release commit not that we cannot release this :smile:

**Comment by jacobstr** [comment]
I'm going to bump the version separately.

**Pull request merged**
