### PR TITLE
move planet data stats interval and filter args to required options

### LINKED ISSUE #887: Update `planet data stats` CLI and python API commands to match `search`
**Expected behavior**
UI of `planet data stats` and `planet data search` should be similar.

**Actual behavior (describe the problem)**
`planet data search` has filter as an option (`--filter`), `planet data stats` has interval and filter as arguments.

**Proposed Solution**

Update `stats` CLI and python API commands to match `search`. Expected command would be `planet data stats PSScene --filter - --interval day` (assuming a filter is piped in).

### PR DESCRIPTION
**Pull request by jreiberkyle**
**Related Issue(s):**

Closes #887 

**Proposed Changes:**

For inclusion in changelog (if applicable):

1. move planet data stats interval and filter args to required options

Not intended for changelog:

1. 

**Diff of User Interface**

Old behavior:

```console
planet data stats PSScene hour filter.json
```

New behavior:

```console
planet data stats PSScene --interval hour --filter filter.json
```

**PR Checklist:**

- [x] This PR is as small and focused as possible
- [x] If this PR includes proposed changes for inclusion in the changelog, the title of this PR summarizes those changes and is ready for inclusion in the Changelog.
- [] I have updated docstrings for function changes and docs in the 'docs' folder for user interface / behavior changes
- [x] This PR does not break any examples or I have updated them

**(Optional) @mentions for Notifications:**
@cholmes I don't see anywhere where the docs reference `planet data stats` so I didn't update nor add any.

### CODE REVIEW

**Comment by cholmes** [comment]
> @cholmes I don't see anywhere where the docs reference planet data stats so I didn't update nor add any.

It's in #891, so in progress. I can update that one after this merges (or vice versa - happy to do the doc updates here if that merges first).

**Review by cholmes — APPROVED** [review]
Tried it out - looks great!

**Review by kevinlacaille — COMMENTED** [review]
When I run the interval for an hour I get a server error, which makes me a little curious as to what's going on. I should note that this filter, `{"type": "AndFilter", "config": []}`, provides results for any other interval. 

```console
> planet data stats PSScene --interval hour --filter filter.json                             

Error: {"general": [{"message": "Item search failed"}], "field": {}}
```

It seems to be unable to provide the stats for the past hour. Should we raise a `ClientError` for this? Also, should we be testing for this?

**Comment by jreiberkyle** [comment]
The failure is on the server side, due to the filter being too broad, this works for me:

```console
 planet data filter --date-range acquired gt 2023-01-01 | planet data stats PSScene --interval hour --filter -
```

**Comment by jreiberkyle** [comment]
since it's a server-side error we won't throw a `ClientError`. The SDK code seems to work as expected so I'll close but happy to reopen if there are concerns.

**Pull request merged**
