### PR TITLE
Quiet download for CLI

### PR DESCRIPTION
**Pull request by kevinlacaille**
- Removed `quiet` flag from Orders
- Added `quiet` flag to global Planet module

cc: @jreiberkyle 
Closing #369

### CODE REVIEW

**Review by mkshah605 — CHANGES_REQUESTED** [review]
Looks great overall! 

Just wondering if we need to keep '-q' as a valid input in both `planet/cli/cli.py` and `tests/unit/test_cli_main.py`? In [this ticket](https://github.com/planetlabs/planet-client-python/issues/365) it says to remove the short options. I'm happy to make this change on my end when I do this ticket but wondering if it would just be easier to implement here?

**Comment by kevinlacaille** [comment]
@mkshah605 That's some really helpful insight, thank you! I've removed the `-q` flag and added some additional valid inputs, similar to how you did in your `--verbosity` ticket. I'll merge with `v2`, if there are no objections :)

**Comment by jreiberkyle** [comment]
hey @kevinlacaille this looks awesome! great teamwork you two! I noticed that somehow [this line](https://github.com/planetlabs/planet-client-python/blob/5fdd0562f4de080cfb4ec04857fbc437d6f70679/planet/cli/cli.py#L37) got duplicated, would you be willing to remove the duplicate line?

**Comment by kevinlacaille** [comment]
> hey @kevinlacaille this looks awesome! great teamwork you two! I noticed that somehow [this line](https://github.com/planetlabs/planet-client-python/blob/5fdd0562f4de080cfb4ec04857fbc437d6f70679/planet/cli/cli.py#L37) got duplicated, would you be willing to remove the duplicate line?

Whoops, looks like I missed this in my merge conflict resolution! Created #467 and will fix on Monday 😊

**Pull request merged**
